### PR TITLE
feature: initiated vue report project and tested sample rendering

### PR DESCRIPTION
**Pull request by sankha555**
* [x] #226 
* [x] Initiated a new ```vue-report``` project in the root directory. Also tested the rendering and project build with sample data. 
* [x] tests passed
* [x] add an entry to the [next release](../release-notes/next-release.md)

### CODE REVIEW

**Comment by sankha555** [comment]
@matthiaskoenig I have made a patch adding sample prototype for the rendering in Vue. I am also attaching a screenshot of the built project for your reference below. I have just tested the rendering of the data for the time being and haven't added any styles for presentation and looks. The data rendering seems to work fine and the live changes are also reflecting on the HTML.
image


Please take a look at it and let me know if I should make any changes and additions to improve it. Thanks!

**Comment by matthiaskoenig** [comment]
@sankha555 This looks great. 
The next step would be to work with an external JSON file which stores the SBML information. I.e. the report should load the information from JSON. 
- [ ] I.e. the json should be part of the index.html or a separate json file next to the index.html which is loaded. This would populate the internal state of the vue.app. 
- [ ] There should be a button which allows to load another JSON as simplest functionality

**Comment by sankha555** [comment]
@matthiaskoenig I have added some functionalities in the ```App.vue``` to load external json files (which are stored in ```assets/test_models``` ) for the rendering. I have also added a form field to upload another JSON file and render the report for that file. Please take a look at the additions in the pull request and please let me know if I should make any changes to improve it. Thanks!

**Comment by matthiaskoenig** [comment]
Things to improve for now:
- [ ] use typescript: https://vuejs.org/v2/guide/typescript.html; we want static typing to avoid errors
- [ ] create a component for rendering and do not use the App.vue for this. I.e create a component SBMLReport which you load in the App.vue
- [ ] Put all styles in separate stylesheet; use SASS/SCSS; see for instance https://medium.com/@mahesh.ks/using-sass-scss-in-vue-js-2-d472af0facf9; Styles should be separate from the app.

- [ ] use local JSON information from external file!

We can not distribute the JSON of the SBMLInfo with the assets because these do not exist when the app is built! I.e. the assets approach will not work. Make the example work with a local JSON. This will be the main challenge for now. How to get a single file which we can send around and it contains the JSON information and the vue app to render it. Loading local files is very challenging with javascript, so one solution could be to directly write the JSON in the index.html (e.g. by using jinja2 from python).
The trick is to store the json information as javascript which you import. See solutions here:
https://stackoverflow.com/questions/19706046/how-to-read-an-external-local-json-file-in-javascript
http://www.askyb.com/javascript/load-json-file-locally-by-js-without-jquery/
Then you have your information `sbmlinfo.json` which is the javascript of the JSON and the index.html which imports the json information. Alternatively you define the json javascript directly in the index.html.

**Comment by sankha555** [comment]
@matthiaskoenig Sure, I will take care of all the points that you have mentioned for the improvements. The modularity of the code into components and stylesheets and typechecking will be my first milestones. Just one clarification regarding the JSON file upload, that I have tried to make it such that the file can be uploaded from anywhere on our system, not only from the assets folder. I had tried it out from a JSON file uploaded from my Desktop and it worked fine. The data from the file is then JSON parsed in the ```readFile()``` method and is used to render the new report. I hope this approach is something similar to what we are looking for. But I would make further improvements to make the application more modular and usable.

I had kept the sample JSON files in ```assets``` just as a temporary storage, but after your explanation I can understand the point that we can't store the models there while the application is built. I will remove those files from ```assets``` and divide the code into components and pass data between these components to achieve the goal. I hope to submit this prototype successfully and this would help me to understand the project better. Thanks a lot for the detailed feedback Sir!

**Comment by sankha555** [comment]
@matthiaskoenig I have made a few changes to add the modularity into components and the use of scss for the styling. While incorporating the styling using scss, a number of errors were coming up due to parsers and importing loaders for the scss. Even after looking out for a long time for the solution, the problem couldn't be fixed and I decided to re-initialize the vue project in the root to start with scss right from the vue-cli (not doing this in the very first attempt was a big mistake on my side, I realized now). I hope the re-initialization would not be a problem for the patch as anyways I was about to refactor the project into components and scss sheets. Please take a look at the work and let me know your feedback about it.

I also wanted to give some updates regarding what I found during my study on Vue for the issue. So for the initial rendering, currently I have kept the representative JSON data as a data object in the ```Report``` component for the time being. So whenever the application loads, the JSON in the data field is rendered by default. I found something called npm's json-server which can be used to host REST APIs from which we can fetch data for our Vue project. If we can use it, we can store the initial JSON in an endpoint of the json-server and make a GET request to the server when the application loads and display that JSON. Do you think this approach could be good for our purpose Sir? 

I will try to look for more improvements that can be done for this issue and implement and update you regarding the same. Please let me know if you have further inputs and reviews that I should incorporate to improve the patch and I would make the required changes to the pull request. Thanks!

**Comment by sankha555** [comment]
A few screenshots of the application after introducing components and changing the UI a bit for each of the components:

Initial rendering with representative data (which I would further replace with an ```sbmlinfo.json``` file or maybe through a json-server endpoint's data)
image

Rendering a test JSON data file
image


In the next update, I would try to keep the initial representative data in a separate json file ```sbmlinfo.json``` and keep it in the project root and render data from it. Hopefully this should get done by the importing the file into the script of ```Report``` and parsing the read contents. I would make the required additions for this change and upload for your reviews and feedback Sir. Thanks!

**Comment by matthiaskoenig** [comment]
@sankha555 This looks very promising.
Yes please fix the static JSON issue next. We don't want a JSON server or similar things. You have to remember the only thing which we can statically distribute is either
- a single report.html (this would be the index.html with a link to the hosted app vue javascript and the included json as <script> tag)
- the report.html and a json file
I.e. the static report you will link will look something like the following (alternatively the JSON not in an external Javascript file but directly in this index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-report</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="https://raw.githubusercontent.com/matthiaskoenig/sbmlutils/feature-vue-prototype/vue-report/sbmlutils-vue-report.js"></script>
    <script src="sbmlinfo.js"></script>
  </body>
</html>
```

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-report</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="https://raw.githubusercontent.com/matthiaskoenig/sbmlutils/feature-vue-prototype/vue-report/sbmlutils-vue-report.js"></script>
    <script>
           data = {"reactions" : [{"name": "Reaction1"}, {"name": "Reaction2"}]};
   </script>
  </body>
</html>
```
Which is rendered with the actual sbmlinfo via python and jinja2. I.e 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-report</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="https://raw.githubusercontent.com/matthiaskoenig/sbmlutils/feature-vue-prototype/vue-report/sbmlutils-vue-report.js"></script>
    <script>
           data = {{ sbmlinfo }}
   </script>
  </body>
</html>
```
This is basically the HTML report from now, just that now all the rendering will be done on the vue side with only the data which should be rendered provided to the report.

**Comment by sankha555** [comment]
@matthiaskoenig Sure Sir, I will try to follow these examples and come up with a solution to load the JSON. Thanks a lot for the detailed explanation Sir!

**Comment by sankha555** [comment]
@matthiaskoenig I have updated the patch to load the initial JSON in the application. I have stored the JSON data in a hidden ```<p>``` tag in ```index.html``` and the JSON is read from this tag. The data in this tag can be rendered using Jinja and Python like you had explained in the example above. This feature could be implemented because of the ```create()``` and ```mount``` (added in ```App.vue```) features provided by Vue which allows to do initial operations when the app first loads. 

Also, I saw the new releases and pulled and rebased them into this branch before pushing the new changes. Please take a look at my work and let me know if we are looking for something like this. Also please let me know what further changes I should make to improve the patch, I would do them and upload for your reviews. Thanks!

**Comment by sankha555** [comment]
Sir I also had a small query regarding the collaborative workflow. The issue is that after I rebased the changes from develop into this branch and pushed the changes, the latest commit that you pushed before get detached and the branch moves to the latest commit (that I made). I am not getting as to why does it move from your commit although I rebased before pushing. 

Could it be due to the force push or should I merge specifically from this branch before pushing my commits? This worries me because a similar thing happened in a previous patch also and I couldn't figure out the reason. I read on this resource https://docs.github.com/en/github/committing-changes-to-your-project/commit-exists-on-github-but-not-in-my-local-clone, should I do something similar to ```git fetch origin``` before rebasing and pushing my changes if there are new changes on the repository? I hope any changes that I might have accidentally on this branch done can be reverted, I am extremely sorry for the inconvenience. Maybe due to my newness in working on a collaborative repository I don't know how to fix this issue but I will learn how to do it. It would be very helpful if you could also give me some solution and pointers regarding this and I would surely take care of this in the future. Thanks!

**Comment by matthiaskoenig** [comment]
This looks very good. The reading from the HTML tags works great. Here we would just inject the JSON information for the static report.
Yes you should fetch all changes first and then rebase against develop. This should normally solve the git issues. The important thing is not too loose any commits.

**Comment by sankha555** [comment]
@matthiaskoenig Thanks a lot for the feedback! Yes I would make sure to first fetch the commits to my local branch and then rebase so as not to lose the commits on the repository, sorry again for the inconvenience caused Sir. 
Regarding the injection into the HTML tags, I suppose we will be using the Jinja rendering with the serialized JSON generated in Python, I hope I am right in this direction. So what should be the next steps that I should take up for this pull request and what other additions and changes I should make to improve the patch? Please let me know your inputs and further suggestions regarding the feature, I would make the required changes to incorporate the improvements. Thanks!

**Comment by matthiaskoenig** [comment]
Closing this. Managed in the sbml4humans branch.

**Pull request closed without merging**
