### PR TITLE
fix: added fstrings and updated file handling in reports module to comply with Python 3 specifications

### LINKED ISSUE #183: Update code fragments in reports module to comply with Python 3
#### Problem description

Please explain:
* **what** some of the code in the reports module like formatting strings and file handling can be updated to Python 3 specifications,
* **how** formatting strings can be replaced by f-strings and files should be opened using the ```with``` construct
* **why** the current code uses some specifications (as mentioned above) from previous releases of Python. These might be deprecated in future releases of Python and it might be difficult to debug and track the updates needed to be done in that case. 

#### Code Sample

As an example,

```
info = '<td id="{}" class="active"><span class="package">{}</span> {}'.format(
    sid, display_sid, meta
)
```
can be replaced by
```
info = f'<td id="{sid}" class="active"><span class="package">{display_sid}</span> {meta}'
```

Also,
```
f_index = codecs.open(index_path, encoding="utf-8", mode="w")
f_index.write(html)
f_index.close()
```
can be replaced by
```
with open(index_path, 'w') as f_index:
    f_index.write(html)
```

For information about the specifications in Python 3 documentation, please see:
[f-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals)
[file handling](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)

### PR DESCRIPTION
**Pull request by sankha555**
* [x] fix #183 
* [x] updated string and file handling in reports module to use fstrings and incorporated use of ```with open()``` construct for file handling
* [x] tests passed

### CODE REVIEW

**Comment by sankha555** [comment]
@matthiaskoenig I have made a patch for the issue in this pull request. Please take a look at it. 

Also, one of the tests (codecov-patch) is failing but I don't seem to find the reason for it. I have run the unittests and black reformatting successfully, but the codecov-patch test seems to report that it is skipping some lines from the code. Kindly let me know what could be a possible reason for this and if I should make any changes to resolve the same. Thanks!

**Comment by matthiaskoenig** [comment]
Normally code coverage should improve on all pull requests by writing additional tests for the code. In your case you removed code lines so the coverage will go down (per total code base). This is okay for such a pull request, but for new features or new code tests are required.

**Review by matthiaskoenig — CHANGES_REQUESTED** [review]
The formating updates look great. But somehow three files were deleted in the pull request?
- ` docs_builder/notebooks/reports/BIOMD0000000012.html`
- ` docs_builder/notebooks/reports/BIOMD0000000012.xml`
-  `src/sbmlutils/converters/xpp_example/results/112836_HH-ext.png`

Can you restore the files or explain why these were removed before I merge?

**Comment by sankha555** [comment]
> Normally code coverage should improve on all pull requests by writing additional tests for the code. In your case you removed code lines so the coverage will go down (per total code base). This is okay for such a pull request, but for new features or new code tests are required.

I understand it now, thanks a lot for the explanation. Sure, I will make it a point to add some tests when I make a PR involving feature and code additions in the future.



> But somehow three files were deleted in the pull request?

I think this happened because I had deliberately deleted these files and regenerated them from the tests to see the working of the tests. Although they still show up in my local repository, I think i accidentally pushed the changed to the commit. I will uncommit this push and make restore the files and make a new commit. I hope that would resolve this.

**Comment by sankha555** [comment]
@matthiaskoenig I have restored the files in the new commits and have squashed the commits into one. Please take a look whether everything is fine now and let me know if I should make any further changes. Sorry for that issue. Thanks!

**Review by matthiaskoenig — APPROVED** [review]

**Pull request merged**
